env: JRUBY_OPTS=--debug
language: ruby

cache:
  bundler: true

sudo: false

before_install:
  - gem update --system
  - gem update bundler
  - bundle --version
  - gem --version

script:
  - make test

notifications:
  email:
    holidaysgem@gmail.com

rvm:
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - jruby-9.0.5.0
  - jruby-9.1.17.0
  - jruby-9.2.0.0
  - 2.5.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
