notifications:
  disabled: true
sudo: false
rvm:
  - ree
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - jruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version
